list = [1,4,7,5,8,2,1,3,4,5,9,7,6,1,10]
a = list.count(1)
b = list.count(2)
c = list.count(3)
d = list.count(4)
e = list.count(5)
f = list.count(6)
g = list.count(7)
h = list.count(8)
i = list.count(9)
j = list.count(10)
print("数字1出现的次数：",a)
print("数字2出现的次数：",b)
print("数字3出现的次数：",c)
print("数字4出现的次数：",d)
print("数字5出现的次数：",e)
print("数字6出现的次数：",f)
print("数字7出现的次数：",g)
print("数字8出现的次数：",h)
print("数字9出现的次数：",i)
print("数字10出现的次数：",j)
